apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: autonomic-demo
  labels:
    app: demo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api
          image: ghcr.io/k8sgpt/k8sgpt:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REQUIRED_FLAG
              value: "true"
            - name: FAIL_EVERY_N
              value: "0"
            - name: STARTUP_DELAY
              value: "0"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
