apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: test-pod
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 31228
